/* Generated By:JavaCC: Do not edit this line. mainConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface mainConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHAR = 1;
  /** RegularExpression Id. */
  int ZERO = 2;
  /** RegularExpression Id. */
  int DIGIT = 3;
  /** RegularExpression Id. */
  int END_STMNT = 4;
  /** RegularExpression Id. */
  int POS = 5;
  /** RegularExpression Id. */
  int NEG = 6;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int DOUBLE = 8;
  /** RegularExpression Id. */
  int ASSIGN = 9;
  /** RegularExpression Id. */
  int NEW = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int DATATYPE = 13;
  /** RegularExpression Id. */
  int COND_OPS = 14;
  /** RegularExpression Id. */
  int REL_OPS = 15;
  /** RegularExpression Id. */
  int READ = 16;
  /** RegularExpression Id. */
  int WRITE = 17;
  /** RegularExpression Id. */
  int SWITCH = 18;
  /** RegularExpression Id. */
  int CASE = 19;
  /** RegularExpression Id. */
  int DEF = 20;
  /** RegularExpression Id. */
  int BREAK = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int FOREACH = 23;
  /** RegularExpression Id. */
  int IN = 24;
  /** RegularExpression Id. */
  int VARNAME = 25;
  /** RegularExpression Id. */
  int STRING = 26;
  /** RegularExpression Id. */
  int COMMENT = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<CHAR>",
    "\"0\"",
    "<DIGIT>",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "<INT>",
    "<DOUBLE>",
    "\"=\"",
    "\"new\"",
    "\"if\"",
    "\"else\"",
    "<DATATYPE>",
    "<COND_OPS>",
    "<REL_OPS>",
    "\"Console.ReadLine\"",
    "\"Console.WriteLine\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"break\"",
    "\"while\"",
    "\"foreach\"",
    "\"in\"",
    "<VARNAME>",
    "<STRING>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"{\"",
    "\"}\"",
    "\"[]\"",
    "\",\"",
    "\"++\"",
    "\"--\"",
    "\"()\"",
    "\"(\"",
    "\")\"",
    "\":\"",
  };

}
